// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopulationAPI.Data;

#nullable disable

namespace PopulationAPI.Migrations
{
    [DbContext(typeof(PopulationDbContext))]
    partial class PopulationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("PopulationAPI.Models.CityPopulation", b =>
                {
                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Country");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.Property<long>("Population")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Population");

                    b.HasKey("City", "Country", "Year");

                    b.ToTable("CityPopulations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
